# Pour la configuration des routes, je me suis référé à un article StackOverflow sur le lien suivant :
# https://stackoverflow.com/questions/77848275/how-to-use-spring-cloud-gateway-mvc-with-a-discovery-client-service-like-eureka
server:
  port: 8000
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}