server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_FOLDER_URI:file:///home/oks/e-comm-project-ms-config-repo}
          default-label: main
      enabled: true
    discovery:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"


#  spring.application.name=config-service
#  server.port=9999
#  #spring.cloud.config.server.git.uri=file:\\D:\\PROJETS\\Spring Course\\bank-account-app\\config-repo
#  spring.cloud.config.server.git.uri=https://github.com/koudjo-simon/bank-account-config-repo
#  spring.cloud.discovery.enabled=true
#  spring.cloud.config.enabled=true
#  eureka.instance.prefer-ip-address=true
#  eureka.server.peer-node-read-timeout-ms=5000
#  eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
#  management.endpoints.web.exposure.include=*
